### ISSUE TITLE
Not possible on existing notes?

### ISSUE THREAD

**Issue by EnidanBri** [makaanneo/joplin-plugin-athena#12]
Hi again,
I don't see a way of making the plugin add the PDF text to existing notes. Is there one? 
If no, would it be difficult to add? 
The could be handled with two tags: 
one tag which you assign to your note(s) when you want the plugin to work on your existing note(s), 
and one tag which the plugin would assign itself to a note when it has finished its work (and remove the first tag)
you could default the two tags to "athena_work" and "athena_finished" and/or make them editable in the settings of the plugin
The plugin could check your notes regularly if it finds any notes with the "athena_work" (or whatever) tag and if it does, process the found notes. Or alternatively, You could create a menu entry to make the plugin process the notes. I had a rough look at your code. Wouldn't that process be a bit similar to the migration code from V1 to V2?
Kind Regards,
Nadine (also from Germany btw :-) )

**Comment by makaanneo** [comment]
Ok that is a new requirement.

I do not considered this so far but could be possible.

To clarify the idea is I do have a note and start the import of any file to a note or the other way I have a note with a pdf attached ( with text ) and the new feature add the text and meta data at the end of the note?

Best regards Sebastian

**Comment by EnidanBri** [comment]
Hi Sebastian,

Thanks for asking for the clarification.

I want to use it on existing notes which already have a PDF (with text)
attached, and I would like to add the PDF text to the end of the note.

Nadine

Sebastian ***@***.***> schrieb am Fr., 16. Dez. 2022, 20:14:

**Comment by EnidanBri** [comment]
Additional info: My use case for this functionality is the migration of my
notes from Evernote to Joplin. I have already all these notes with PDF
attachments (exported from Evernote in ENEX format and imported into
Joplin). Evernote was able to search the PDF contents on its own, but
Joplin isn't, so I need to add the PDF text to the notes.

Nadine Brinkmann ***@***.***> schrieb am So., 18. Dez.
2022, 01:25:

**Comment by makaanneo** [comment]
Hi Nadine,

ok, yes, I am on it, take a while ... may this week.

May in the future to search in PDFs content will be built into Joplin.

I take some assumption:
1. a Note has more than one resource attached (any type)
2. the feature will create the metadata block (with content) for each resource.
3. The function will be useable similar to the migrate feature

Best
Regards
Sebastian

**Comment by EnidanBri** [comment]
Great! Thanks a lot! 👍 😃

**Comment by makaanneo** [comment]
@EnidanBri I did some work a new version is there (2.2.0) may it will take some time to see it in Joplin plugin overview.
